---

- name: clusterverse | Deploy (and/or delete) the cluster VMs
  hosts: localhost
  gather_facts: false
  tasks:
    - assert: { that: "['clusterverse.clusterverse', 'dseeley.tasks_serial', 'dseeley.ansible_vault_pipe'] is subset(galaxy_collections.keys())", success_msg: "clusterverse collections dependencies are met", fail_msg: "Please ensure the clusterverse collections are installed: ansible-galaxy install -r requirements.yml)" }
      vars: { galaxy_collections: "{{lookup('pipe', 'ansible-galaxy collection list --format=json', errors='ignore') | from_json | json_query('*') | combine }}" }
      tags: ["always"]

    - block:
        - { include_role: { name: "clusterverse.clusterverse._dependencies", apply: { tags: ["always"]} }, tags: ["always"] }
        - { include_role: { name: "fluentd/clean", apply: { tags: ["always"]} }, tags: ["always"], when: clean == '_all_' }
        - { include_role: { name: "clusterverse.clusterverse.clean", apply: { tags: ["clusterverse_clean"]} }, tags: ["clusterverse_clean"] }
      when: "clean is defined"

    - { include_role: { name: "clusterverse.clusterverse.create", apply: { tags: ["clusterverse_create"]} }, tags: ["clusterverse_create"] }
    - { include_role: { name: "clusterverse.clusterverse.dynamic_inventory", apply: { tags: ["always"]} }, tags: ["always"] }

- name: clusterverse | Configure the cluster VM OSs (excluding not-being-redeployed hosts)
  hosts: all:!not_target_hosts
  gather_facts: false
  tasks:
    - { wait_for_connection: "", timeout: 300, tags: ["always"] }
    - { include_role: { name: "clusterverse.clusterverse.config", apply: { tags: ["clusterverse_config"]} }, tags: ["clusterverse_config"] }


###### fluentd roles ######
- name: fluentd | load clusterverse dependencies (if excluded due to --skips-tags)
  hosts: all:!not_target_hosts
  tasks:
    - { include_role: { name: "clusterverse.clusterverse._dependencies", apply: { tags: ["always"] } }, tags: ["always"], when: "'clusterverse_config' not in ansible_run_tags" }      # If we --skip-tags=clusterverse_config, this will ensure the variables from /cluster_defs are loaded.
    - { include_role: { name: "clusterverse.clusterverse.cluster_hosts", apply: { tags: ["always"] } }, tags: ["always"], when: "'clusterverse_create' not in ansible_run_tags" }      # If we --skip-tags=clusterverse_create, this will ensure cluster_suffix is defined.

- name: fluentd | ssl_ownca
  hosts: all:!not_target_hosts
  tasks: [ { include_role: { name: "fluentd/ssl_ownca", apply: { tags: ["fluentd_ssl_ownca"] } }, tags: ["fluentd_ssl_ownca"] } ]

- name: fluentd | Install and configure
  hosts: all:!not_target_hosts
  tasks: [ { include_role: { name: "fluentd/build", apply: { tags: ["fluentd_build"] } }, tags: ["fluentd_build"] } ]
######


- name: clusterverse | Perform cluster readiness operations. 'post_deploy.yml' is run after every cluster deploy; 'post_redeploy.yml' is run after redeploy (or cluster deploy if this is not a redeploy)
  hosts: localhost
  tasks:
    - { include_role: { name: "clusterverse.clusterverse.readiness", tasks_from: "post_deploy.yml" } }
    - { include_role: { name: "clusterverse.clusterverse.readiness", tasks_from: "post_redeploy.yml", apply: { tags: ["clusterverse_readiness"]} }, tags: ["clusterverse_readiness"] }
