---

roles:
  - name: clusterverse
    src: https://github.com/dseeley/clusterverse
    version: master

  - name: fluentd
    src: https://github.com/dseeley/fluentd-ansible
    version: master

collections:
  - name: dseeley.ansible_vault_pipe
    source: https://galaxy.ansible.com
