---

- name: fluentd/redeploy_predelete | hosts_to_remove
  debug: msg="{{hosts_to_remove | default([])}}"

- block:
    - name: fluentd/redeploy_predelete | Stop fluentd service
      become: true
      service:
        name: fluentd
        state: stopped
      delegate_to: "{{ item.name }}"
      with_items: "{{ hosts_to_remove }}"

    - name: fluentd/redeploy_predelete | reapply loadbalancer config, excluding hosts_to_remove
      include_role:
        name: 'fluentd/build'
        tasks_from: fluentd-loadbalancer.yml
      vars:
        fluentd_cluster_filters:
          "tag:cv__cluster_name": "{{cluster_name}}"
          "tag:Name": "{{ groups['all'] | reject('in', hosts_to_remove | map(attribute='name') | list) | list }}"
      when: groups['fluentd'] | length > 1
  when: hosts_to_remove | length > 0