---

merge_dict_vars_list:
  - "./cluster_defs/"
  - "./cluster_defs/{{ cloud_type }}/"
  - "./cluster_defs/{{ cloud_type }}/{{ region | default() }}/"
  - "./cluster_defs/{{ cloud_type }}/{{ region | default() }}/{{ buildenv | default() }}/"
