---

merge_dict_vars_list:
  - "{{playbook_dir}}/cluster_defs/"
  - "{{playbook_dir}}/cluster_defs/{{ cloud_type }}/"
  - "{{playbook_dir}}/cluster_defs/{{ cloud_type }}/{{ region }}/"
  - "{{playbook_dir}}/cluster_defs/{{ cloud_type }}/{{ region }}/{{ buildenv }}/"
